image: alpine/latest
oauth: pages.sr.ht/PAGES:RW
packages:
  - hut
sources:
  - https://git.sr.ht/~mgh/wch
tasks:
  - package: |
      cd wch
      tar -czf ../site.tar.gz \
        index.html \
        script.js \
        styles.css
  - deploy: |
      hut pages publish -d mgh.srht.site:wch site.tar.gz
